In [1]:
import numpy as np

In [12]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))
print(np.log(np.exp(1))) # natural log of e is 1.0
print(np.exp(1)) # this is e
print(np.pi) # this is pi

-1.0
1.1
5.2
1.0
2.718281828459045
3.141592653589793


In [13]:
#np arrays are vectors in reality
vec = np.array([1,2,3])

In [14]:
print(vec)

[1 2 3]


In [65]:
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(mat)

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [66]:
mat_transpose = mat.T
print(mat_transpose)
print(print(mat.T))

[[1 4 1]
 [2 5 8]
 [1 9 9]]
[[1 4 1]
 [2 5 8]
 [1 9 9]]
None


In [67]:
# other ways to create arrays
vec2 = np.arange(0,15) # 0 is inclusive and 15 is exclusive
print(vec2)
vec3 = np.arange(3,21,6) # in steps of 6
print("")
print(vec3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [68]:
vec4 = np.linspace(0,5,10) # 0 and 15 both are inclusive and there would 10 equispced data point
print(vec4)
print("")
vec5 = vec4.reshape(5,2) # 5 rows and 2 columns
#vec5 = np.reshape(vec4) # does not work
print(vec5)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [69]:
mat2 = np.zeros([5,3]) # matrix of 0's 5 rows and 3 columns using a list []
print(mat2)
print("")
mat3 = np.ones((3,5))# this itme using tuples of 3 and 5 ()
print(mat3)
print("")
mat4 = np.eye(5) # square matrix of 5x5 with identity all 1's in diagonal
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Part 2 of numpy video


In [70]:
# +, -, *, / of arrays -- arrays should of same size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec6-vec5)
print(vec6*vec5)
print(vec6/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[2 2 2 2 2]
[ 3  8 15 24 35]
[3.         2.         1.66666667 1.5        1.4       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [48]:
# matrix multiplication

print(mat)
print("")
print(vec)
print()
prod = np.matmul(mat, vec)  # dot products of rows and colums https://www.mathsisfun.com/algebra/matrix-multiplying.html
# row item * rows item and add them
#1*1+ 2*2 + 3*3 = 14
#4*1+ 5*2 + 6*3 = 32
#1*7+ 2* 8 + 3*9 = 50
print(prod)
prod2 = np.matmul(vec, mat)
print("change the order of multipliar")
print(prod2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3]

[14 32 50]
change the order of multipliar
[30 36 42]


In [101]:
# solving a matrix is like m1*m2 = prod and we know m1 and prod and want to find m2 
print(mat)
print(vec)
prod = np.matmul(mat, vec)
print(prod)
print()
print(mat)
print(prod)
print()
mat7 = np.linalg.solve(mat, prod)

print(mat7)


[[1 2 1]
 [4 5 9]
 [1 8 9]]
[1 2 3]
[ 8 41 44]

[[1 2 1]
 [4 5 9]
 [1 8 9]]
[ 8 41 44]

[1. 2. 3.]


In [72]:
print(np.matmul(mat, mat7))
print(np.matmul(mat, vec))

[14. 32. 50.]
[ 8 41 44]


In [ ]:
### NOTE : there seems more then one solution

In [73]:
# inverse of a matrix A*inv(A) = Identity matrix

print(mat)
inv_mat = np.linalg.inv(mat)
print(inv_mat)
print(np.matmul(mat, inv_mat))

[[1 2 1]
 [4 5 9]
 [1 8 9]]
[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [78]:
mt = np.array([[1,2,3],[4,5,6],[7,8,9]])
vt = np.array([1,2,3])
print(mt)
print(vt)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


In [106]:
###########################

#print(mat)
#inv_mat = np.linalg.inv(mat)
#print(inv_mat)
#print(np.matmul(mat, inv_mat))

print(mt)
print(vt)

#inv_mt = np.linalg.inv(mt)
#print(inv_mt)
#print(np.matmul(mt, vt))
#print(np.linalg.solve(mt, prd)

prd=np.matmul(mt, vt)

print(prd)
print()
print(np.linalg.solve(mt, prd))

inv_mt = np.linalg.inv(mt)
print(inv_mt)
print(np.matmul(mt, inv_mt))
#print(np.linalg.solve(mt, prd)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[14 32 50]

[2. 0. 4.]
[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
[[ 0.  0.  0.]
 [-4.  0. -4.]
 [ 0.  0.  0.]]


In [115]:
####### test another for inversion

matrix1 = np.array([[1,2],[6,7]])
print(matrix1)
vector1 = np.array([3,9])
print(vector1)
print("--------------")
inv_matrix1 = np.linalg.inv(matrix1)
print(inv_matrix1)
print(np.matmul(matrix1, inv_matrix1))

pr = np.matmul(matrix1, vector1)
print("--------------")
print(pr)
print(np.linalg.solve(matrix1, pr))

[[1 2]
 [6 7]]
[3 9]
--------------
[[-1.4  0.4]
 [ 1.2 -0.2]]
[[1. 0.]
 [0. 1.]]
--------------
[21 81]
[3. 9.]


In [118]:
# finding unique values

vec7 = np.array(["ram", "Ram", "Shyam", "Radhey", "ram", "india", "india", "Bharat", 100])
print(vec7)
print(np.unique(vec7))

['ram' 'Ram' 'Shyam' 'Radhey' 'ram' 'india' 'india' 'Bharat' '100']
['100' 'Bharat' 'Radhey' 'Ram' 'Shyam' 'india' 'ram']


In [123]:
# numpy to generate data
rand_mat = np.random.rand(5,5) # sqaure matrix of 5 x 5 data point Uniform random variable - mean = 0.5
print(rand_mat)
print("--------------")
rand_mat2 = np.random.randn(10,5) # Standard normal random variable - mean = 0 std = 1
print(rand_mat2)
print("--------------")
print(np.mean(rand_mat))
print(np.std(rand_mat2))
print("--------------")
print(np.min(rand_mat))
print(np.max(rand_mat2))

[[0.69616139 0.79374618 0.47493851 0.26855588 0.66912752]
 [0.74370571 0.31120309 0.54724701 0.45541322 0.33214942]
 [0.80176713 0.50114604 0.25665586 0.61819527 0.38316454]
 [0.20945406 0.34871887 0.9628901  0.09884685 0.24083419]
 [0.17567078 0.97632248 0.21122567 0.89765886 0.2102141 ]]
--------------
[[ 0.90701837 -1.71235423  0.81673326  1.20162197 -0.74738931]
 [ 1.46773947  0.02817868  0.19200072 -0.73964274 -0.35028461]
 [ 0.03926674 -0.06541551  1.8738723  -0.33722135  0.37576495]
 [ 0.40793708  0.58187648  1.82417552  2.03135104  1.20170237]
 [-0.47079939  0.12479734  0.27543969 -0.10235288 -1.41145997]
 [ 0.41963938  0.53056426  0.10364277  0.22618478 -0.78034595]
 [ 1.17713307 -1.27010795  0.28962054 -0.16284578 -0.18805358]
 [-0.82389868 -0.20118333  1.29232797  1.59731179 -0.67694832]
 [-2.10117567  0.97493727 -1.13286247 -1.03262135 -0.25786876]
 [-0.11391308  1.37285046 -0.46397711 -0.05219461  1.15510139]]
--------------
0.4874005093876162
0.9446344866454721
----------

In [127]:
rand_vec = np.random.randn(19)
print(rand_vec)
print("--------------")
print(rand_vec[6])
print("--------------")
print(rand_vec[4:10])

[ 0.83961611 -0.14111241 -0.65933041 -1.23326729  1.10560613  0.48308482
  0.21748731  0.38061462 -1.00609406  1.073796    0.01509803  1.68195713
  0.53705381 -0.03726785 -1.13458384  0.21169889  1.42501089  0.38126848
  2.49394487]
--------------
0.2174873113258187
--------------
[ 1.10560613  0.48308482  0.21748731  0.38061462 -1.00609406  1.073796  ]


In [131]:
print(rand_vec[np.arange(0,15,3)])

[ 0.83961611 -1.23326729  0.21748731  1.073796    0.53705381]


In [138]:

print(rand_mat)
print("_________________________________________________________")
print(rand_mat[1][2])
print(rand_mat[1,2])

[[0.69616139 0.79374618 0.47493851 0.26855588 0.66912752]
 [0.74370571 0.31120309 0.54724701 0.45541322 0.33214942]
 [0.80176713 0.50114604 0.25665586 0.61819527 0.38316454]
 [0.20945406 0.34871887 0.9628901  0.09884685 0.24083419]
 [0.17567078 0.97632248 0.21122567 0.89765886 0.2102141 ]]
_________________________________________________________
0.5472470142203053
0.5472470142203053


In [149]:
rand_vec = np.random.randn(19)
print(rand_vec)
rand_vec[3:5] = 4
rand_vec[3:5] = [1,2] # list to can be provied for change of data point
print("_________________________________________________________")
print(rand_vec)


[-1.04997784  0.93228771 -1.91030892 -0.39848221 -0.76792191 -1.17341506
  0.77752929 -0.56749077  0.09100738 -0.4513532   1.58781083 -1.00289488
 -1.29488623 -0.17697606 -0.18909934 -1.66539009 -0.3257162   0.9883707
 -0.54966062]
_________________________________________________________
[-1.04997784  0.93228771 -1.91030892  1.          2.         -1.17341506
  0.77752929 -0.56749077  0.09100738 -0.4513532   1.58781083 -1.00289488
 -1.29488623 -0.17697606 -0.18909934 -1.66539009 -0.3257162   0.9883707
 -0.54966062]


In [154]:
print(rand_mat)
rand_mat[1:4, 1:4] = 0
print("_________________________________________________________")
print(rand_mat)

[[0.69616139 0.79374618 0.47493851 0.26855588 0.66912752]
 [0.74370571 0.         0.         0.45541322 0.33214942]
 [0.80176713 0.         0.         0.61819527 0.38316454]
 [0.20945406 0.34871887 0.9628901  0.09884685 0.24083419]
 [0.17567078 0.97632248 0.21122567 0.89765886 0.2102141 ]]
_________________________________________________________
[[0.69616139 0.79374618 0.47493851 0.26855588 0.66912752]
 [0.74370571 0.         0.         0.         0.33214942]
 [0.80176713 0.         0.         0.         0.38316454]
 [0.20945406 0.         0.         0.         0.24083419]
 [0.17567078 0.97632248 0.21122567 0.89765886 0.2102141 ]]


In [160]:
# sub matrix extraction
rand_mat[1:4, 1:4] = 0
print(rand_mat)
print("_________________________________________________________")
sub_mat = rand_mat[1:4, 1:4] # with 0's
print(sub_mat)
print("_________________________________________________________")
sub_mat[:] = 3 # ITN this would modify the rand_mat as well ..... with 3's
print(sub_mat)
print("_________________________________________________________")
print(rand_mat)

[[0.69616139 0.79374618 0.47493851 0.26855588 0.66912752]
 [0.74370571 0.         0.         0.         0.33214942]
 [0.80176713 0.         0.         0.         0.38316454]
 [0.20945406 0.         0.         0.         0.24083419]
 [0.17567078 0.97632248 0.21122567 0.89765886 0.2102141 ]]
_________________________________________________________
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
_________________________________________________________
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
_________________________________________________________
[[0.69616139 0.79374618 0.47493851 0.26855588 0.66912752]
 [0.74370571 3.         3.         3.         0.33214942]
 [0.80176713 3.         3.         3.         0.38316454]
 [0.20945406 3.         3.         3.         0.24083419]
 [0.17567078 0.97632248 0.21122567 0.89765886 0.2102141 ]]


In [164]:
sub_mat2 = rand_mat[0:3, 0:3].copy()
print(sub_mat2)

[[0.69616139 0.79374618 0.47493851]
 [0.74370571 3.         3.        ]
 [0.80176713 3.         3.        ]]


In [170]:
sub_mat2[:] = 100
print(sub_mat2)
print("_________________________________________________________")
print(rand_mat) # original is not modified

[[100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]]
_________________________________________________________
[[0.69616139 0.79374618 0.47493851 0.26855588 0.66912752]
 [0.74370571 3.         3.         3.         0.33214942]
 [0.80176713 3.         3.         3.         0.38316454]
 [0.20945406 3.         3.         3.         0.24083419]
 [0.17567078 0.97632248 0.21122567 0.89765886 0.2102141 ]]


In [171]:
##### saving and loading numpy

In [177]:
rand_vec = np.random.randn(15)
print(rand_vec)
print()
print(rand_vec > 0)
print(rand_vec[rand_vec >0]) # prints only the True values

[ 1.04727289 -0.27390223  1.3810504  -0.83076545 -0.8252655   1.07144494
 -1.62320273  1.90748176  1.06098089  1.27600883 -2.74343448  0.91913145
 -0.96570877  0.77901459  0.88566334]

[ True False  True False False  True False  True  True  True False  True
 False  True  True]
[1.04727289 1.3810504  1.07144494 1.90748176 1.06098089 1.27600883
 0.91913145 0.77901459 0.88566334]


In [184]:
print(rand_vec) 

rand_vec[rand_vec > .5] = 5 
print(rand_vec)

[ 5.         -0.27390223  5.         -0.83076545 -0.8252655   5.
 -1.62320273  5.          5.          5.         -2.74343448  5.
 -0.96570877  5.          5.        ]


[ 5.         -0.27390223  5.         -0.83076545 -0.8252655   5.
 -1.62320273  5.          5.          5.         -2.74343448  5.
 -0.96570877  5.          5.        ]


In [185]:
print(rand_mat2)
print()
print()
print(rand_mat2[rand_mat2 > 0])

[[ 0.90701837 -1.71235423  0.81673326  1.20162197 -0.74738931]
 [ 1.46773947  0.02817868  0.19200072 -0.73964274 -0.35028461]
 [ 0.03926674 -0.06541551  1.8738723  -0.33722135  0.37576495]
 [ 0.40793708  0.58187648  1.82417552  2.03135104  1.20170237]
 [-0.47079939  0.12479734  0.27543969 -0.10235288 -1.41145997]
 [ 0.41963938  0.53056426  0.10364277  0.22618478 -0.78034595]
 [ 1.17713307 -1.27010795  0.28962054 -0.16284578 -0.18805358]
 [-0.82389868 -0.20118333  1.29232797  1.59731179 -0.67694832]
 [-2.10117567  0.97493727 -1.13286247 -1.03262135 -0.25786876]
 [-0.11391308  1.37285046 -0.46397711 -0.05219461  1.15510139]]


[0.90701837 0.81673326 1.20162197 1.46773947 0.02817868 0.19200072
 0.03926674 1.8738723  0.37576495 0.40793708 0.58187648 1.82417552
 2.03135104 1.20170237 0.12479734 0.27543969 0.41963938 0.53056426
 0.10364277 0.22618478 1.17713307 0.28962054 1.29232797 1.59731179
 0.97493727 1.37285046 1.15510139]


In [188]:
# saving some araay to a file
np.save('save_rand_mat2', rand_mat2) #  np.savez is for zip'ing multiple numpy array

In [190]:
loaded_vec = np.load('save_rand_mat2.npy') # while loading it would be .npz
print(loaded_vec)

[[ 0.90701837 -1.71235423  0.81673326  1.20162197 -0.74738931]
 [ 1.46773947  0.02817868  0.19200072 -0.73964274 -0.35028461]
 [ 0.03926674 -0.06541551  1.8738723  -0.33722135  0.37576495]
 [ 0.40793708  0.58187648  1.82417552  2.03135104  1.20170237]
 [-0.47079939  0.12479734  0.27543969 -0.10235288 -1.41145997]
 [ 0.41963938  0.53056426  0.10364277  0.22618478 -0.78034595]
 [ 1.17713307 -1.27010795  0.28962054 -0.16284578 -0.18805358]
 [-0.82389868 -0.20118333  1.29232797  1.59731179 -0.67694832]
 [-2.10117567  0.97493727 -1.13286247 -1.03262135 -0.25786876]
 [-0.11391308  1.37285046 -0.46397711 -0.05219461  1.15510139]]


In [197]:
# numpy can save the array in .txt as well
# np.savetxt('file name', array, delimiter=',')
# loadtxt()
np.savetxt('save_rand_mat2.txt', rand_mat2, delimiter=',') # saves as comma dilited text file