## Single Dimension NumPy Array

In [8]:
import numpy as np
n1=np.array([10,20,30,40])
n1
print(n1)
n1

[10 20 30 40]


array([10, 20, 30, 40])

## Multi Dimensional Arrays

In [18]:
#import numpy as np
n2 = np.array([[10,20,20,20],[50,60,60,80]])
n2
print(n2)
n2
#type([[],[]])
type(n2)

[[10 20 20 20]
 [50 60 60 80]]


numpy.ndarray

## Multidimension with '0' as Data

In [22]:
# array of 1-Row and 3-Columns 
n3=np.zeros((1,3))
n3    

array([[0., 0., 0.]])

In [23]:
# array of 5-Row and 5-Columns 
n4=np.zeros((5,5))
n4 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Multidimension with a 'Value' as Data

In [50]:
n5=np.full((5,5), 10)
n5
print(n5.shape)
print(n5)

(5, 5)
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [211]:
n6=np.arange(2,12)
n6


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
# array would be between 100-199
n6b = np.arange(100,200)
n6b
n6b.shape

(100,)

In [38]:
# with predfined incrament
n7=np.arange(-14, -0, 2)
n7

array([-14, -12, -10,  -8,  -6,  -4,  -2])

## Random Number Genration

In [212]:
# 1-100 range nad 10 is number generated
n8 = np.random.randint(1,120,12)
n8

array([101,   1,  96,  41, 118,  75,  91,  16,  52,  41,  63,  65])

## Shape

In [57]:
# shape is aan attribute not a funtion
n8.shape

(12,)

In [51]:
## Shape

In [60]:
n8.shape = (4,3)
n8


array([[ 69,  29,   8],
       [  7,  46,  11],
       [ 36,  10, 110],
       [ 38,  33,  78]])

## vstack(), hstack(), cloumn_stack() methods

In [64]:
#vstack
ns1 = np.array([1,2,3,4])
ns2 = np.array([5,6,7,8])
nss = np.vstack((ns1, ns2))
nss

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
#hstack
nh1 = np.array([1,2,3,4])
nh2 = np.array([5,6,7,8])
nhs = np.hstack((nh1, nh2))
nhs

array([1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
#column_stack
nc1 = np.array([1,2,3,4])
nc2 = np.array([5,6,7,8])
ncs = np.column_stack((nc1, nc2))
ncs

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## Intersection and Diffenece Methods

In [69]:
# Intercetion retunr common elements
ni1 = np.array([10,20,20,40,50,60])
ni2 = np.array([70, 60, 50, 80])
np.intersect1d(ni1,ni2)

array([50, 60])

In [70]:
# unique to ni1
np.setdiff1d(ni1,ni2)

array([10, 20, 40])

In [71]:
# unique to ni2
np.setdiff1d(ni2,ni1)

array([70, 80])

## Maths with NumPy Arrays

In [76]:
# additiong Elelemnts
a1 = np.array([10,20])
a2 = np.array([30,40])
print(np.sum([a1, a2])) # all element are added
print(np.sum([a1, a2], axis=0)) # array column wise element added
print(np.sum([a1, a2], axis=1)) # array row  wise element added

100
[40 60]
[30 70]


## Maths with NumPy Arrays - scaler values
## operation is performed on each eement in array

In [83]:
b1 = np.array([10,20])
print(b1)

[10 20]


In [84]:
b1 = b1 + 1

In [85]:
b1

array([11, 21])

In [87]:
b1-1

array([10, 20])

In [88]:
b1

array([11, 21])

In [89]:
b1*2

array([22, 42])

In [90]:
b1/2

array([ 5.5, 10.5])

## Statristics Operation

In [91]:
# Meam Value

so = np.array([2,3,7,6,8,5,6,7,3,4,6,7,])
np.mean(so)

5.333333333333333

In [94]:
np.median(so)

6.0

In [96]:
np.std(so)

1.8408935028645432

In [99]:
so.size

12

In [101]:
so.sum()


64

In [102]:
so.mean()

5.333333333333333

In [103]:
so.sum()/so.size

5.333333333333333

In [104]:
so.std()

1.8408935028645432

## NymPy Matrix

In [107]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
m1[1]

array([4, 5, 6])

In [111]:
# we extract first colunm as array
m1[:,0]

array([1, 4, 7])

In [124]:
m1[0:][0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
# Transposing a Matrxi - interchangng Row iwht Columns
m1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## NymPy Matrix - Multiplication is .dot operation

In [130]:
print(" m1 array")
print(m1)
print("")
print(" m2 array")
m2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(m2)

 m1 array
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 m2 array
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [131]:
m1.dot(m2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [132]:
m2.dot(m1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

## Saving ang Loading NumPy Array

In [134]:
print(so)
np.save('my-numpy',so)

[2 3 7 6 8 5 6 7 3 4 6 7]


In [137]:
sos=np.load('my-numpy.npy')
sos

array([2, 3, 7, 6, 8, 5, 6, 7, 3, 4, 6, 7])

In [139]:
print(m2)
np.save('M2',m2)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [140]:
M2L = np.load('M2.npy')
M2L

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

## Pandas ---  Data Manupulation & Analysis


### Pandas Series 

In [153]:
import pandas as pd
# labeled series
sr1 = pd.Series([1,2,3,4,5])
sr2 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
print(sr1)
print("")
print(sr2)
                


0    1
1    2
2    3
3    4
4    5
dtype: int64

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [144]:
type(sr1)

pandas.core.series.Series

### Creatng key: value pair with dictionaries in Pandas

In [154]:
pd.Series({'a':10, 'b' : 20, 'c': 30})

a    10
b    20
c    30
dtype: int64

In [155]:
dic1 = {'a':10, 'b' : 20, 'c': 30}

In [156]:
pd.Series(dic1)

a    10
b    20
c    30
dtype: int64

In [161]:
# changing the Inded position as per the Index
s3 = pd.Series({'a':10, 'b' : 20, 'c': 30}, index=['d','b','a','c','e'])
s3

d     NaN
b    20.0
a    10.0
c    30.0
e     NaN
dtype: float64

In [162]:
s4 = pd.Series([1,2,3,4,5,6,7,8,9])

In [163]:
s4[1]

2

In [164]:
s4[0:3]

0    1
1    2
2    3
dtype: int64

In [165]:
s4[3:]

3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [166]:
s4[:]

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [171]:
s4[3:-1]

3    4
4    5
5    6
6    7
7    8
dtype: int64

In [174]:
# last three elements
s4[-3:]

6    7
7    8
8    9
dtype: int64

## Math operation on  pandas Series

In [175]:
# scaler Operations
s4 +10

0    11
1    12
2    13
3    14
4    15
5    16
6    17
7    18
8    19
dtype: int64

In [179]:
s5 = pd.Series([10,20,30,40,50,60,70,80,90])

In [180]:
print(s4)
print(s5)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
dtype: int64


In [178]:
s4 + s5

0    11
1    22
2    33
3    44
4    55
5    66
6    77
7    88
8    89
dtype: int64

In [181]:
s5-s4

0     9
1    18
2    27
3    36
4    45
5    54
6    63
7    72
8    81
dtype: int64

In [183]:
s5**s4

0                    10
1                   400
2                 27000
3               2560000
4             312500000
5           46656000000
6         8235430000000
7      1677721600000000
8    387420489000000000
dtype: int64

## Dataframe is Pandas 2-Dimnsional Labeled Datastructure

In [188]:
# Dict keys are Column Names and values are columns Data
df1 = pd.DataFrame({"Name":["Sharad","Priya","Adu"], "Marks":[78, 88,99]})

In [189]:
df1

Name  Marks
0  Sharad     78
1   Priya     88
2     Adu     99

In [190]:
type(df1)

pandas.core.frame.DataFrame

In [196]:
iris = pd.read_csv('iris.csv')

In [197]:
iris.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [198]:
iris.head(10)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

In [199]:
iris.tail()

sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [200]:
iris.shape

(150, 5)

In [201]:
iris.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [203]:
iris.iloc[0:4,0:2]

sepal.length  sepal.width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2
3           4.6          3.1

In [207]:
iris.iloc[140
          :,3:]

petal.width    variety
120          2.3  Virginica
121          2.0  Virginica
122          2.0  Virginica
123          1.8  Virginica
124          2.1  Virginica
125          1.8  Virginica
126          1.8  Virginica
127          1.8  Virginica
128          2.1  Virginica
129          1.6  Virginica
130          1.9  Virginica
131          2.0  Virginica
132          2.2  Virginica
133          1.5  Virginica
134          1.4  Virginica
135          2.3  Virginica
136          2.4  Virginica
137          1.8  Virginica
138          1.8  Virginica
139          2.1  Virginica
140          2.4  Virginica
141          2.3  Virginica
142          1.9  Virginica
143          2.3  Virginica
144          2.5  Virginica
145          2.3  Virginica
146          1.9  Virginica
147          2.0  Virginica
148          2.3  Virginica
149          1.8  Virginica

In [209]:
iris.loc[0:3, ("sepal.length","sepal.width") ]

sepal.length  sepal.width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2
3           4.6          3.1

In [210]:
iris.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [215]:
from scipy.stats import chi2_contingency
data=[400, 100],[200,1300]
stat, p, dof, expected = chi2_contingency(data)
print(stat, p, dof, expected)

790.479365079365 6.339192746569971e-174 1 [[ 150.  350.]
 [ 450. 1050.]]


In [217]:
from scipy.stats import f
f.ppf(q=1-0.05, dfn = 2, dfd = 27)

3.3541308285291986