In [1]:
import numpy as np

In [2]:
print(np.cos(np.pi))

-1.0


In [8]:
np.pi

3.141592653589793

In [9]:
print(np.sqrt(np.pi))

1.7724538509055159


In [11]:
np.log(np.exp(5.2))

5.2

In [12]:
np.exp(1)

2.718281828459045

In [15]:
# we are getting value of 'e'
np.log(np.exp(np.exp(1)))

2.718281828459045

In [19]:
vec4=np.linspace(0,9,10)
print(vec4)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [20]:
vec4.reshape(5,2)

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [26]:
mat6=np.eye(5)
print(mat6)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
vecn=np.random.randn(40)
print(vecn)

[ 0.23240772  0.46630874  0.4760114  -2.29533905  0.28632185  0.65183437
 -0.71741492 -0.34193836 -0.72033053  0.09165032 -2.57681982 -0.777995
 -1.04186544 -0.08899147  0.11497298 -0.93514996 -0.24868775 -1.30123322
  0.07473712  0.28676503  0.59527855 -0.99467328  0.0870994   0.85855093
  0.9799953   0.50252702 -1.70052105  1.22392576  0.91964638 -1.75207644
 -0.56597316  0.53049037 -0.14787342  0.21504091  0.03991861 -1.52534332
  1.64723959  0.70897603  1.83397656 -2.63425347]


In [30]:
vecn.mean()

-0.18857011806743823

In [31]:
vecn.std()

1.0630483473382868

In [32]:
vecn.min()

-2.634253474397477

In [33]:
vecn.max()

1.833976563075123